<?php

namespace cervezaBundle\Repository;

/**
 * cervecitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cervecitasRepository extends \Doctrine\ORM\EntityRepository
{
}
